### ISSUE TITLE
Use `on_create` and `always` instead of `true/false` for `generate_value` flag

### ISSUE THREAD

**Issue by verkaufer** [1Password/ansible-onepasswordconnect-collection#11]
The simple `true/false` value for `generate_value` can be confusing:
- Does `true` mean the value is generated every time I run the playbook?
- Does `true` mean the value will always overwrite the previous value?
- Does `false` mean a previous value is preserved? 

The `community.aws` module uses `on_create` and `always` in the module that [creates new IAM users](https://github.com/ansible-collections/community.aws/blob/36f8a0586835731baa6c2824f51f79d7e2c55eec/plugins/modules/iam.py#L83-L90). I think this is a clearer way to explain that generating a value can be a one-time operation or occur every time the playbook is run.

In practice this would look like:
```
  onepassword.connect.generic_item:
    title: Club Membership
    state: created
    fields:
      - label: Secret Code
        field_type: concealed
        generate_value: on_create   # value will only be generated once; future playbook executions will not change the value
        generator_recipe:
            length: 16
            include_letters: yes
            include_digits: yes
            include_symbols: no
        section: Club Card Details
```
