### ISSUE TITLE
Cannot connect to 1Password Connect container

### ISSUE THREAD

**Issue by vladzaharia** [1Password/ansible-onepasswordconnect-collection#13]
### Your environment

Collection Version: 1.0.1
Connect Server Version: 1.1.0
OS: Ubuntu 20.04
Ansible Version: 2.9.6

## What happened?
I'm trying to query and upsert records in my Ansible playbooks via AWX. Whenever I attempt to use any of the modules, I get

```
fatal: [10.10.0.189]: FAILED! => {"changed": false, "msg": "Connection failure: [Errno 104] Connection reset by peer", "op_item": {}}
```

In the API container's logs, I see 200 entries for the GETs, but don't see the POSTs I would expect with an upsert.

## What did you expect to happen?
Record to be retrieved and/or upserted.

## Steps to reproduce
1. Use the example playbook
2. Execute either locally or on the remote host via Ansible AWX

## Notes & Logs
```
The full traceback is:

  File "/tmp/ansible_onepassword.connect.generic_item_payload_gdp77psh/ansible_onepassword.connect.generic_item_payload.zip/ansible_collections/onepassword/connect/plugins/modules/generic_item.py", line 282, in main

  File "/tmp/ansible_onepassword.connect.generic_item_payload_gdp77psh/ansible_onepassword.connect.generic_item_payload.zip/ansible_collections/onepassword/connect/plugins/module_utils/vault.py", line 57, in upsert_item

    original = api_client.get_item_by_name(vault_id, item_name)

  File "/tmp/ansible_onepassword.connect.generic_item_payload_gdp77psh/ansible_onepassword.connect.generic_item_payload.zip/ansible_collections/onepassword/connect/plugins/module_utils/api.py", line 81, in get_item_by_name

    return self._get_item_id_by_name(vault_id, item_name)

  File "/tmp/ansible_onepassword.connect.generic_item_payload_gdp77psh/ansible_onepassword.connect.generic_item_payload.zip/ansible_collecti…
```

**Comment by verkaufer** [comment]
Thanks for taking the time to file this issue! 

If you could answer a couple troubleshooting questions, I can help get this resolved:
1. Are you running the API server behind a proxy or using TLS? 

2. Did the Connect API server logs contain errors for a request to this URL:
   `/vaults/{vault_id}/items?filter=title eq "<name of item>"`

3. I noticed that the request is failing for `get_item_id_by_name`. Does this still happen if you provide the item UUID? You could test this in a non-destructive way by using the `onepassword.connect.item_info` module with the item UUID:
```
 onepassword.connect.item_info:
   item: <item id>
   vault: <vault id>
```

**Comment by vladzaharia** [comment]
Thanks for following up @verkaufer! Happy to provide more data.

1. API is running straight up on HTTP, only difference is that API is running on 9080 and Syncer on 9081 on a bridged network, but otherwise just took the docker-compose and ran it.

2. No errors whatsoever for these calls. I was getting some 400 bad requests when I played around with supplying vault names instead of IDs in the Ansible playbook, but when I queried all by IDs, or by vault ID and item name, it always came back with 200s:

```
{"log_message":"(I) GET /v1/vaults/<snip>/items/<snip>","timestamp":"2021-05-04T00:18:33.686475947Z","level":3,"scope":{"request_id":"150c1671-1917-41fd-8d1d-fe4571d0cdd9"}}
```

and

```
{"log_message":"(I) GET /v1/vaults/<snip>/items?filter=title%20eq%20%22<snip>%22 completed (200: OK)","timestamp":"2021-05-03T23:52:58.629370443Z","level":3,"scope":{"request_id":"e4177ea3-570c-4dec-a35e-72f779f4a8e9","jti":"7tjg3gl6vknyns3qrrswzmb2qi"}}
```

3. Yep, definitely tried that. I created a quick nodejs app using the SDK and tested out the calls to make sure the API was running successfully and it worked fine. Took the item ID of the same item I was trying to query but neither worked in the Ansible playbook.

**Comment by verkaufer** [comment]
Appreciate the extra details! I'll try to reproduce on my end and let you know what I find.

**Comment by vladzaharia** [comment]
Of course! Happy to try things on my end.

One thing I didn't try is running the playbook locally, but I do suspect it's a result of running this all through Ansible Tower/AWX. I did try using `connection:local` to have it run on the machine running Ansible rather than the one connecting to, and that made no difference.

**Comment by verkaufer** [comment]
Back again after doing some research. 

I was able to run this example successfully using this playbook:
<details>
<summary>Example Playbook</summary>

```yml
---

- name: Testing 1Password Secrets Automation
  connection: local
  gather_facts: false
  hosts: localhost # running directly on my machine/controller
  environment:
    OP_CONNECT_HOST: http://localhost:8080
    OP_CONNECT_TOKEN: "<snip>"
  tasks:
    - name: Create 1Password Secret
      onepassword.connect.generic_item:
        title: Club Membership
        vault_id: "<snip>"
        state: created
        fields:
          - label: Codeword
            value: "hunter2"
            section: "Personal Info"
            field_type: concealed
      register: op_item

    - name: Display the config
      debug:
        msg: "{{op_item}}"
```
</details>

**Note**: I ran this on my own machine, and did not run this inside a Docker container or using AWX to manage the playbook execution.

### Research 

I did some searching for AWX and the `connect reset by peer` error and noticed a couple other people reporting similar issues when running tasks via AWX:
- https://github.com/ansible/awx/issues/1861 (allegedly solved in AWX v2.0.1, and this issue is nearly 3 years old)
   - Potential solution: https://github.com/ansible/awx/issues/1861#issuecomment-410975920
 
I'll admit I have limited experience with AWX and I haven't tried using AWX with this playbook, so I'm not sure if it could be affecting outbound network connections to the Connect API server. 

I also found this issue that notes the problem **may be related to how sockets are configured to handle Keep-Alive requests**: https://github.com/psf/requests/issues/4937#issuecomment-773321262 . 

We're using the Ansible-provided `fetch_url` function and as a result, we're using whatever defaults Ansible sets when preparing a network request.

### Next Steps

Can I ask you to try running the playbook on your machine and not via AWX? That will help determine if the issue is with some networking setting related to AWX or not.
