### ISSUE TITLE
Need clarification in item_info example

### ISSUE THREAD

**Issue by johnwarburton** [1Password/ansible-onepasswordconnect-collection#35]
### Summary
Need example clarification in https://github.com/1Password/ansible-onepasswordconnect-collection#examples

### Use cases
The *Find a field by name* example mixes 'Admin Password' and 'Admin Username'

### Proposed solution
Either make the example the most common use case of _retrieving a password_ the actual example:
```
  tasks:
    - name: Get the 'Admin Password' field from the 'Staging Database' item
      item_info:
        item: Staging Database
        vault: Staging Env 
        field: Admin Password  # find field named "Admin Password"
      no_log: true
      register: op_item

    - name: Print the password
      ansible.builtin.debug:
        var: "{{ op_item.field }}"
```
or line up the name to be  'Admin Username' in the name label:
```
  tasks:
    - name: Get the 'Admin Username' field from the 'Staging Database' item
      item_info:
        item: Staging Database
        vault: Staging Env 
        field: Admin Username  # find field named "Admin Username"
      no_log: true
      register: op_item

    - name: Print the username
      ansible.builtin.debug:
        var: "{{ op_item.field }}"
```
### Is there a workaround to accomplish this today?
In my proof of concept documentation, I used the first proposed example
```
  tasks:
    - name: Get the password field from the "POC item read test" item in the vault "POC"
      item_info:
        item: POC item read test
        vault: POC
        field: password
      no_log: true
      register: op_item

    - name: print the password
      ansible.builtin.debug:
        msg: "password is: '{{ op_item.field }}'"
```

### References & Prior Work
NA
