### ISSUE TITLE
Fields of Login type items are not retrieved 

### ISSUE THREAD

**Issue by hculea** [1Password/ansible-onepasswordconnect-collection#41]
### Your environment

Collection Version: 2.1.1

Connect Server Version: 1.4

OS: MacOS 12.0.1

Ansible Version: 2.11.0

## What happened?
I tried to retrieve a Login type item, with multiple fields, aside from "Username" and "Password", some that were within sections, some that were not. I noticed that, aside from "Username" and "Password", only the fields within sections have been retrieved. The fields that weren't in sections were not retrieved.
## What did you expect to happen?
I expected all the fields to be retrieved.
## Steps to reproduce

1. Create a LOGIN type item, and add, below username and password, another field.
2. Retrieve it with the Ansible Collection, using the script below:
```yaml
---
- name: "test playbook"
  hosts: localhost
  environment:
    OP_CONNECT_HOST: http://localhost:8080
    OP_CONNECT_TOKEN: "<your-token>"
  collections:
    - onepassword.connect
  tasks:
    - name: "get item"
      item_info:
        item: <item-name>
        vault: <vault-uuid>
        flatten_fields_by_label: false   # might need to omit this line, depends on the collection version that you run 
      no_log: true
      register: op_item
    - name: show dictionary
      debug:
        msg: "{{item}}"
      with_dict: "{{ op_item.op_item }}"
```
You'll see that no fields that are not within a section, other than username and password, will be there.

## Notes & Logs

Not relevant.
