### ISSUE TITLE
Fix TOTP field type

### ISSUE THREAD

**Issue by verkaufer** [1Password/ansible-onepasswordconnect-collection#46]
### Your environment

Collection Version: 2.1.1

Connect Server Version: 1.5.0

OS: n/a

Ansible Version: n/a

## What happened?

The Connect server rejects requests where an item field type is set to "TOTP". This is not a valid field type; instead, the client should send "OTP".

## What did you expect to happen?

Item is created successfully. 

## Steps to reproduce
1. Run `ansible-playbook playbook.yml`

with the following playbook:
```yaml
---
- name: Create an item and generate its value if the item does not exist.
  onepassword.connect.generic_item:
    title: Item with OTP
    state: present
    fields:
      - label: Secret Code
        field_type: totp # this is invalid, it should be 'otp'
        value: "otpauth://totp/Example:steve@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Example"
```

The Connect server will reject this request because `field_type: totp` is invalid.

## Notes & Logs

* Related to https://github.com/1Password/connect/pull/26
