### ISSUE TITLE
Adding URLs to LOGIN items not working

### ISSUE THREAD

**Issue by gaborpeter** [1Password/ansible-onepasswordconnect-collection#49]
### Summary
After adding a LOGIN item with Ansible, and then visiting the site with the browser, 1Password client was not pulling it up as a suggestion even though the item was present and URL was correct.

### Use cases
I followed the documentation how to create the item:
```
- name: Create 1pass item for admins
  onepassword.connect.generic_item:
    vault_id: "***"
    title: "Admin access"
    category: login
    state: present
    fields:
      - label: Username
        value: "admin"
        field_type: string
      - label: Password
        value: "***"
        field_type: concealed
      - label: website
        value: "https://yourdomain.com/login"
        field_type: url
  no_log: true
```
It did successfully create the item, but it added it under an empty "section" even though in the definition no section assignment was requested. After analyzing the tool I've seen that, you can add the URL's outside of sections and when they are placed there (kind of root level) then it works like a charm.

### Proposed solution
I found in the 1Password API documentation that there is an "url" property for each item, which can be used. So when I added an item as follows, it did the trick and 1Password client suggested the item after properly when visiting the URL:
```
- name: Create 1pass item for admins
  onepassword.connect.generic_item:
    vault_id: "***"
    title: "Admin access"
    category: login
    state: present
    urls: 
      - "https://yourdomain.com/login"
    fields:
      - label: Username
        value: "admin"
        field_type: string
      - label: Password
        value: "***"
        field_type: concealed
  no_log: true
```
Probably this could be added to the documentation.
