### ISSUE TITLE
400 Bad request when using item/field name

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/ansible-onepasswordconnect-collection#58]
### Your environment

Collection Version: v2.2.0

Connect Server Version: 1.5.1

OS: MacOS

Ansible Version: ansible [core 2.13.0]

## What happened?

When I use the name of the secret instead of its uuid, I get a 400 error.

## What did you expect to happen?

Secret returned successfully

## Steps to reproduce
1. Set up a secret like this
```
- name: Find basic auth for monitoring cluster.
  item_info:
    item: cluster-basic-auth
    vault: monitoring
  no_log: true
  register: op_item
```

## Notes & Logs

```
Monday 27 June 2022  16:50:49 +0200 (0:00:00.362)       0:00:00.369 *********** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Server returned error with invalid JSON: HTTP Error 400: Bad Request"}```
