### ISSUE TITLE
Example for field_info not correct

### ISSUE THREAD

**Issue by rooso** [1Password/ansible-onepasswordconnect-collection#67]
Collection Version 2.2.0

Connect Server Version: n/a

OS: n/a

Ansible Version: core 2.13.1

## What happened?
The example in this README.MD is not correct. If the Ansible Module `debug` is used with `var` a variable is expected. With your example you got the error `<class 'dict'>": "VARIABLE IS NOT DEFINED!: ` as debug output.

```
---
  hosts: localhost
  environment:
    OP_CONNECT_HOST: http://localhost:8001
    OP_CONNECT_TOKEN: "valid.jwt.here"
  collections:
    - onepassword.connect
  tasks:
    - name: Find a field labeled "username" in an item named "MySQL Database" in a specific vault.
      onepassword.connect.field_info:
      item: MySQL Database
      field: username
      vault: 2zbeu4smcibizsuxmyvhdh57b6
    no_log: true
    register: op_item

    - name: Print the field definition
      ansible.builtin.debug:
        var: "{{ op_item.field }}"
```

Please change the last line in your example to the following:

```
        msg: "{{ op_item.field }}"
```

This will might save someone's valuable time in searching for solution :)
