### ISSUE TITLE
onepassword.connect.generic_item state=absent task fails if item is present

### ISSUE THREAD

**Issue by gav-** [1Password/ansible-onepasswordconnect-collection#70]
### Your environment

Collection Version: 2.2.1

Connect Server Version: 1.5.7

OS: Ubuntu 20.04

Ansible Version: 
ansible==5.9.0
ansible-core==2.12.7

## What happened?

Running `onepassword.connect.generic_item` module as a task, with state=absent returns FAILED when the item is present in the 1Password vault. The item is correctly deleted however. The error is the same if either "title" or "uuid" parameters are used. No error is returned if the item is not present in the vault. 

## What did you expect to happen?
Ansible should complete the task as 'ok'

## Steps to reproduce
1. Make sure that "myitem" is in the 1Password vault
2. Simple ansible task to delete "myitem" from 1Password vault:
```
- name: Ensure myitem is NOT in 1password Ansible vault
  onepassword.connect.generic_item:
    hostname: '{{ onepassword_connect_host }}'
    token: '{{ onepassword_connect_token }}'
    vault_id: '{{ onepassword_vault_id }}'
    title: myitem
    state: absent
  connection: local
  register: op_item
```
3. Ansible returns:
```
TASK [onepassword : Ensure myitem is NOT in 1password Ansible vault] ***************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "OK (unknown bytes)", "op_item": {}}
```
