### ISSUE TITLE
Ability to use vault title in field.info module

### ISSUE THREAD

**Issue by volodymyrZotov** [1Password/ansible-onepasswordconnect-collection#74]
### Your environment

Collection Version: 2.2.1

Connect Server Version: 1.5.7

OS: MacOS

Ansible Version: 7.4.0

## What happened?
When using `vault_title` instead of the `vault_id` in the playbook, the `Vault ID invalid or undefined.` error is thrown.

## What did you expect to happen?
Successfully find item field using `vault_title`

## Steps to reproduce
1. Run the next playbook
```
---
- name: "test playbook"
  hosts: localhost
  environment:
    OP_CONNECT_HOST: http://localhost:8080
    OP_CONNECT_TOKEN: "<token>"
  collections:
    - onepassword.connect
  tasks:
    - name: "Field info example"
      field_info:
        item: redis
        vault: title
        field: username
      no_log: false
      register: op_item
```
2. See the `Vault ID invalid or undefined.` is printed.
