### ISSUE TITLE
Use of environment variables leaks credentials

### ISSUE THREAD

**Issue by vdoflip** [1Password/ansible-onepasswordconnect-collection#76]
### Your environment
Collection Version: 2.2.1
Ansible Version: 2.14.5

## What happened?
When using the plugins with the `OP_CONNECT_HOST` and `OP_CONNECT_TOKEN` env vars, these values are leaked in the logs when they are in high verbosity (verbosity=4 for example).

The logs show this line:
`<localhost> EXEC /bin/sh -c 'OP_CONNECT_HOST=http://onepassword-connect.external-secrets.svc.cluster.local:8080 OP_CONNECT_TOKEN=eJsd**redacted**xCrs /usr/bin/python3 /runner/.ansible/tmp/ansible-tmp-1682684835.9986675-57-256536358333729/AnsiballZ_item_info.py && sleep 0'`

As mentioned in the Ansible docs:

> Environment variables are normally passed in clear text (shell plugin dependent) so they are not a recommended way of passing secrets to the module being executed.

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_environment.html

This is a critical issue in automation environments with multi tenancy like AWX.

## Solution

This can be avoided simple passing the host and token as parameters, and setting `no_log: true`, like in the example:

```
    - name: Get some key
      delegate_to: localhost
      onepassword.connect.item_info:
        hostname: "{{ op_connect_host }}"
        token: "{{ op_connect_token }}"
        vault: "somevault"
        item: "key"
      register: onepassword_key
      no_log: true
```

Given the nature of these tokens, I think this alternative should be documented in the README, and maybe even as the default.
